version: "3.9"

services:
  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "apk add --no-cache tzdata && npm install && npm run dev -- --host"

  backend:
    image: node:20-alpine
    container_name: backend
    working_dir: /app
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "apk add --no-cache tzdata && npm install && npm run dev"

